add pm and temperature function
dev-jko/github-repo-chatbot pull request #28
Opened 2019-02-07 23:45 UTC by podojuice

2019-02-07 23:45 UTC, podojuice commented
어제한거 푸시해놓고 pull request를안했네요 ..

2019-02-09 04:42 UTC, dev-jko requested changes
api key 값들 환경변수 쓰는걸로 바꿔주세요

2019-02-11 10:34 UTC, podojuice reviewed
환경변수고침

2019-02-11 10:39 UTC, dev-jko approved these changes

2019-02-11 10:40 UTC, merged